import { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ThemeToggle } from "@/components/theme-toggle";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import SignIn from "@/components/sign-in";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Header() {
  return (
    <header
      className={cn(
        "sticky top-0 w-full flex justify-between p-4 bg-white border-b border-gray-200",
        "dark:border-gray-800 dark:bg-gray-950"
      )}
    >
      <Link
        href="/"
        className={cn(
          "p-1 text-cyan-500 font-bold text-xl",
          "dark:text-gray-100"
        )}
      >
        Todo List
      </Link>
      <div className="flex gap-2 items-center">
        <ThemeToggle />
        <Button variant="secondary" className="cursor-pointer" asChild>
          <Link href="/login">Sign In</Link>
        </Button>
        <Button className="cursor-pointer" asChild>
          <Link href="/register">Sign Up</Link>
        </Button>
      </div>
    </header>
  );
}

function Footer() {
  return (
    <footer
      className={cn(
        "bottom-0 w-full bg-gray-100 border-t border-gray-200",
        "dark:bg-gray-900 dark:border-gray-800"
      )}
    >
      <div className="container mx-auto px-4 py-6">
        <div className="flex justify-between items-center">
          <div className={cn("text-sm text-gray-600", "dark:text-gray-400")}>
            © {new Date().getFullYear()} Todo List App. All rights reserved.
          </div>
          <div className="flex gap-4">
            <Link
              href="/about"
              className={cn(
                "text-sm text-gray-600 hover:text-gray-900",
                "dark:text-gray-400 dark:hover:text-gray-100"
              )}
            >
              About
            </Link>
            <Link
              href="/privacy"
              className={cn(
                "text-sm text-gray-600 hover:text-gray-900",
                "dark:text-gray-400 dark:hover:text-gray-100"
              )}
            >
              Privacy Policy
            </Link>
            <Link
              href="/terms"
              className={cn(
                "text-sm text-gray-600 hover:text-gray-900",
                "dark:text-gray-400 dark:hover:text-gray-100"
              )}
            >
              Terms of Service
            </Link>
          </div>
        </div>
      </div>
    </footer>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={"antialiased"}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          // disableTransitionOnChange
        >
          <Header />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
